AWSTemplateFormatVersion: 2010-09-09
Description: Crea los roles de IAM necesarios para las instancias
Resources:
  RolEC2SSM:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action: "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
  PerfilInstanciaEC2SSM:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref RolEC2
      Path: "/"
Outputs:
  PerfilInstanciaSSM:
    Description: Perfil de la instancia con permisos para registrarse con AWS SSM
    Value: !Ref PerfilInstanciaEC2SSM
